version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
      google:
        patterns:
          - "google.golang.org/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions:
        patterns:
          - "*"
